name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/graalvm/graalvm-ce:latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        mvn install
